dist: xenial
sudo: required

language: python

cache: pip

python:
  - 2.7

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

env:
  - REQUIREMENTS=pip
  - REQUIREMENTS=pipenv

install:
  - pip install .
  - if [[ $REQUIREMENTS == pip ]]; then pip install -r requirements.txt && pip install -r requirements_dev.txt; fi
  - if [[ $REQUIREMENTS == pipenv ]]; then pip install -U pipenv==2018.11.26 && pipenv sync --dev; fi

before_script:
  - cd tests/data && ./download.sh && cd ../..
  - cd tests/data && python -m download && cd ../..

script:
  - py.test

notifications:
  on_failure: always
  on_success: change
