dist: xenial
sudo: required

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

before_script:
  - cd tests/data && ./download.sh && cd ../..
  - cd tests/data && python -m download && cd ../..

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then py.test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 || $TRAVIS_PYTHON_VERSION == 3.6 || $TRAVIS_PYTHON_VERSION == 3.7 || $TRAVIS_PYTHON_VERSION == nightly ]]; then pytest; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then coverage run --source=arpa setup.py test; fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then coveralls; fi

notifications:
  on_failure: always
  on_success: change
